name: Katanas
version: '2.0'
main: me.greefox.greefox.me.Greefox.Katanas
api-version: 1.19
authors: [ GreeFox ]
description: Adds craftable Katanas!
commands:
  givekatana:
    description: "Gives player a katana"
    usage: /<command> <item> <player>
  #reloadkatanas:
  #  description: "Reloads the config!"
  #  usage: /<command>
  katanas:
    description: "Shows help for Katans plugin"
    usage: /<command>